### ISSUE TITLE
Too Broad Exception Raised

### ISSUE THREAD

**Issue by tatarize** [KaivnD/pypolybool#4]
You throw an Exception classed Exception which is generally too broad of an exception to catch.

```python
                    raise Exception(
                        "PolyBool: Zero-length segment detected; your epsilon is probably too small or too large"
                    )
```

```python
class PolyBoolException(Exception):
    pass
```

Then throw that, so that people can catch the exception without catching all exceptions.

**Comment by KaivnD** [comment]
ok，that's better, will do.
